# Generated by Django 5.1.5 on 2025-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Surname", models.CharField(max_length=30)),
                ("number", models.CharField(max_length=30)),
                ("mail_address", models.CharField(max_length=30)),
                ("product", models.CharField(max_length=30)),
            ],
        ),
    ]
