# Generated by Django 5.1.5 on 2025-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="Name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="person",
            name="Surname",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="person",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
