# Generated by Django 5.1.5 on 2025-02-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_person_name_alter_person_surname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="Surname",
            new_name="surname",
        ),
    ]
