# Generated by Django 5.1.5 on 2025-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_name_person_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("surname", models.CharField(max_length=15)),
                ("number", models.IntegerField(default=0)),
                ("mail_address", models.CharField(max_length=30)),
                ("product", models.CharField(max_length=30)),
            ],
        ),
    ]
