# Generated by Django 5.1.5 on 2025-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_person_table_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="number",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="person",
            name="product",
        ),
        migrations.AlterModelTable(
            name="order",
            table=None,
        ),
        migrations.AlterModelTable(
            name="person",
            table=None,
        ),
    ]
