# Generated by Django 5.1.6 on 2025-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "in processing"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="orders", to="food.product"),
                ),
            ],
        ),
    ]
